apiVersion: v1
kind: Service
metadata:
  name: accounts
  labels:
    app: accounts
    service: accounts
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    service: accounts